### ISSUE TITLE
can't create reference file with model type resnet_50_arc !

### ISSUE THREAD

**Issue by OnlinePage** [Ant-Brain/EfficientWord-Net#30]
Hi been trying to create the new reference file with below command
`python -m eff_word_net.generate_reference --input-dir ./mywakewordaudios --output-dir ./ --wakeword mywakeword --model-type resnet_50_arc`

Also seems like when generating audio for the same wakeword using generate audio command I was getting 500 response, maybe api request is being limited.

But I created around 8 audios(1-1.5s long) of my wake word using audacity and yet failed to create reference file using resnet_50_arc. However with  First_Iteration_Siamese reference file is being easily created.

here is the error trace I got:
`eff_word_net\audio_processing.py", line 199, in audioToVector
    assert inpAudio.shape == (self.window_frames, ) #1.5 sec long window`

**Comment by TheSeriousProgrammer** [comment]
its a minor bug it will be helpful if you could share your audio files to recreate the error

**Comment by zerocool-11** [comment]
I had this similar issue, I fixed it by recording the hot word samples for 2 seconds instead of 1
but when i run the inference script it throws a similar error 
```
    assert inpAudio.shape == (self.window_frames, ) #1.5 sec long window
AssertionError
```
i am attaching both [json](https://github.com/zerocool-11/utitlies/blob/main/pluto_ref.json) file and my [inference code](https://github.com/zerocool-11/utitlies/blob/main/wakeword.py) to recreate the error

`EfficientWord-Net Version: 1.0.2`

**Comment by TheSeriousProgrammer** [comment]
Have recently made a commit which should fix the same, however its not up in the pypi repo yet, can you try installing from source using github?

**Comment by zerocool-11** [comment]
hi @TheSeriousProgrammer  thanks, it's working fine now though it often throws this error 
`OSError: [Errno -9981] Input overflowed`
to fix this, I just updated your [stream.py](https://github.com/Ant-Brain/EfficientWord-Net/blob/f99a8d26406418a0ef4c886b4e3a8fe1a8b6cabb/eff_word_net/streams.py#L94) in line number 94
to this
 ```

get_next_frame = lambda : (
                np.frombuffer(mic_stream.read(CHUNK,exception_on_overflow = False),dtype=np.int16)
            ),
```
I just passed the exception_on_overflow as False in the pyaudio stream read function

I just wanted to let you know so that you could add it to your next commit, maybe...

**Comment by TheSeriousProgrammer** [comment]
that sounds good , can you make a pr of the same?

**Comment by zerocool-11** [comment]
Done... :) 
 @TheSeriousProgrammer
